// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Init

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
AppendStructuredBuffer<int> particlePool;
AppendStructuredBuffer<int> connectionPool;



[numthreads(256,1,1)]
void Init (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    particlePool.Append(index);
    connectionPool.Append(index);   
}
